AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  GBServerLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: gb-server:latest
      Timeout: 30
      Environment:
        Variables:
          MONGODB_URI: ""
          MONGODB: ""
          ASAAS_BASE_URL: ""
          ASAAS_API_KEY: ""
